version: 0.0

os: linux

hooks:

files:
   - source: /
     destination: /

BeforeInstall:

   - location: codeDeployFolder/stopServer.sh

     runas: root


AfterInstall:

   - location: codeDeployFolder/startServer.sh

     runas: root