version: 0.0

os: linux

hooks:

files:
   - source: /
     destination: /var/www

BeforeInstall:

   - location: /var/www/codeDeployFolder/stopServer.sh

     runas: root


AfterInstall:

   - location: /var/www/codeDeployFolder/startServer.sh

     runas: root